### ISSUE TITLE
Dead Link in Tutorial? 

### ISSUE THREAD

**Issue by michael-baur-techlabs** [googlecodelabs/google-maps-simple-store-locator#20] opened 2020-10-15 23:09 UTC
https://codelabs.developers.google.com/codelabs/google-maps-simple-store-locator/#4
has a step:

Run the following command in Cloud Shell to download the marker and logo graphics. Make sure you're in the store-locator directory. Use Control+C to stop the simple HTTP server if it's running.:

`$ mkdir -p img; wget https://storage.googleapis.com/gmaps-store-locator/assets.zip -O temp.zip; unzip temp.zip -d img; rm temp.zip`

[https://storage.googleapis.com/gmaps-store-locator/assets.zip](url) is a dead link.

 mkdir -p img; wget https://storage.googleapis.com/gmaps-store-locator/assets.zip -O temp.zip; unzip temp.zip -d img; rm temp.zip
--2020-10-15 23:09:09--  https://storage.googleapis.com/gmaps-store-locator/assets.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.142.128, 74.125.195.128, 2607:f8b0:400e:c08::80, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.142.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-15 23:09:09 ERROR 404: Not Found.
Archive:  temp.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of temp.zip or
        temp.zip.zip, and cannot find temp.zip.ZIP, period.

Press F to pay respects, or maybe it will get hosted again soon, thanks for taking a look

**Comment by wangela** [comment] 2020-11-25 02:04
Duplicate of #15

**Closed by wangela** 2020-11-25 02:04 UTC
