### ISSUE TITLE
Max destinations?

### ISSUE THREAD

**Issue by krjo** [googlecodelabs/google-maps-simple-store-locator#14] opened 2020-04-11 21:31 UTC
If you have more than 25 locations in our json file this will not work. Is there a work around or another solution for calculating distances for more than 25 stores? Or is it possible to get only the destinations that are in view at the current zoom level?

**Comment by wangela** [comment] 2020-04-28 09:21
The 25 store limit is due to the Distance Matrix API's limit of a [max of 25 origins or 25 destinations per request](https://developers.google.com/maps/documentation/distance-matrix/usage-and-billing#other-usage-limits). The "[Filtering the data](https://codelabs.developers.google.com/codelabs/nyc-subway-station-locator/#5)" step of the NYC Subway Stations Locator codelab has logic for displaying only the stations within the visible bounds of the map, and the step after that teaches you how to cluster groups of markers.

**Comment by wangela** [comment] 2020-11-25 02:09
Duplicate of #12

**Closed by wangela** 2020-11-25 02:09 UTC
